### ISSUE TITLE
No icons on button

### ISSUE THREAD

**Issue by android116** [AlejandroAkbal/Image-to-Text-OCR#2]
I came across that after I did **npm start**,
In the area for dragging the image, there is no picture icon, there is no icon on the "Extract text" button.
After the text is recognized, there is also no icon on the "copy to clipboard" button
and because of this, even if you press this button, then copying to the clipboard does not occur.

I noticed that when executing **npm run build** an error slipped
```
rendering chunks (7)...Failed to fetch web fonts
FetchError: request to https://fonts.googleapis.com/css2?family=DM+Sans&family=DM+Serif+Display&family=DM+Mono&display=swap failed, reason: connect ETIMEDOUT 64.233.161.95:443()
```

I started googling about it and found out that some module is trying to download fonts from there
DM Sans
DM Serif Display
DM Mono

I assumed that the icons are taken from these fonts. Did I guess right?

I found a mention of them in the unocss.config.ts file and found that if googleapis is not available, you can try to write
`provider: 'bunny',`
or
`provider: 'fontshare',`
in **unocss.config.ts**

But that didn't work, I still get the Failed to fetch web fonts error, it's just that the other addresses it's trying to download fonts from are no longer available.
I thought that perhaps npm does not know how to go through a proxy server and applied everything that I found on this issue on stackoverflow.
Nothing helped.

Then I downloaded these fonts and placed them in the directory of my server, where all ttf fonts are located, and in **unocss.config.ts**
indicated
`provider: 'none',`
judging by the documentation, this should force you to look for fonts in the system directory.
npm run build started to run without errors, but the icons on the buttons did not appear.

I don't understand all these npm and other terrible web stuff, but maybe somewhere in some config
explicitly set the path to these damn fonts?

**Comment by AlejandroAkbal** [comment]
Hey @android116 

Unfortunately icons are not loaded by a CDN from Google fonts, they are installed locally with NPM using Iconify, have you run "npm run dev"? That should work for local development

**Comment by android116** [comment]
> Hey @android116
> 
> Unfortunately icons are not loaded by a CDN from Google fonts, they are installed locally with NPM using Iconify, have you run "npm run dev"? That should work for local development

This is what I have when I do **npm run build**  (var/www/vhosts/ocr - catalog with Image-to-Text-OCR):

```
root@host var/www/vhosts/ocr # npm run build

> @ build /var/www/vhosts/ocr
> nuxi build

Nuxi 3.1.1                                                                                                    09:55:37
Nuxt 3.1.1 with Nitro 2.1.1-27917995.930438a                                                                  09:55:37
ℹ Building client...                                                                                          09:55:44
vite v4.0.4 building for production...
✓ 214 modules transformed.
rendering chunks (7)...Failed to fetch web fonts
FetchError: request to https://fonts.googleapis.com/css2?family=DM+Sans&family=DM+Serif+Display&family=DM+Mono&display=swap failed, reason: connect ETIMEDOUT 64.233.161.95:443 ()
    at async $fetchRaw2 (file:///var/www/vhosts/ocr/node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
    at async $fetchRaw2 (file:///var/www/vhosts/ocr/node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
    at async $fetchRaw2 (file:///var/www/vhosts/ocr/node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
    at async importUrl (/var/www/vhosts/ocr/node_modules/unocss/node_modules/@unocss/preset-web-fonts/dist/index.cjs:102:14)
    at async Object.getCSS (/var/www/vhosts/ocr/node_modules/unocss/node_modules/@unocss/preset-web-fonts/dist/index.cjs:120:33)
    at async file:///var/www/vhosts/ocr/node_modules/@unocss/core/dist/index.mjs:568:110
    at async Promise.all (index 1)
    at async file:///var/www/vhosts/ocr/node_modules/@unocss/core/dist/index.mjs:567:33
    at async Promise.all (index 0)
    at async file:///var/www/vhosts/ocr/node_modules/@unocss/core/dist/index.mjs:565:9
    at async UnoGenerator.generate (file:///var/www/vhosts/ocr/node_modules/@unocss/core/dist/index.mjs:552:5)
    at async generateAll (file:///var/www/vhosts/ocr/node_modules/@unocss/vite/dist/index.mjs:328:18)
    at async Object.renderChunk (file:///var/www/vhosts/ocr/node_modules/@unocss/vite/dist/index.mjs:395:23)
    at async transformChunk (file:///var/www/vhosts/ocr/node_modules/rollup/dist/es/shared/rollup.js:16620:16)
    at async file:///var/www/vhosts/ocr/node_modules/rollup/dist/es/shared/rollup.js:16681:17
    at async Promise.all (index 0)
    at async transformChunksAndGenerateContentHashes (file:///var/www/vhosts/ocr/node_modules/rollup/dist/es/shared/rollup.js:16677:5)
    at async renderChunks (file:///var/www/vhosts/ocr/node_modules/rollup/dist/es/shared/rollup.js:16598:109)
    at async Bundle.generate (file:///var/www/vhosts/ocr/node_modules/rollup/dist/es/shared/rollup.js:16807:13)
    at async file:///var/www/vhosts/ocr/node_modules/rollup/dist/es/shared/rollup.js:25030:27
    at async catchUnfinishedHookActions (file:///var/www/vhosts/ocr/node_modules/rollup/dist/es/shared/rollup.js:24133:20)
    at async doBuild (file:///var/www/vhosts/ocr/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44518:22)
    at async Module.build (file:///var/www/vhosts/ocr/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44347:16)
    at async buildClient (file:///var/www/vhosts/ocr/node_modules/@nuxt/vite-builder/dist/shared/vite-builder-edge.bd2158aa.mjs:370:5)
    at async bundle (file:///var/www/vhosts/ocr/node_modules/@nuxt/vite-builder/dist/shared/vite-builder-edge.bd2158aa.mjs:903:3)
    at async build (file:///var/www/vhosts/ocr/node_modules/nuxt3/dist/index.mjs:2469:5)
    at async Object.invoke (file:///var/www/vhosts/ocr/node_modules/nuxi/dist/chunks/build.mjs:56:5)
    at async _main (file:///var/www/vhosts/ocr/node_modules/nuxi/dist/cli.mjs:51:20)
.nuxt/dist/client/manifest.json                                  2.89 kB
.nuxt/dist/client/_nuxt/error-500.aa16ed4d.css                   1.95 kB │ gzip:  0.74 kB
.nuxt/dist/client/_nuxt/error-404.23f2309d.css                   3.63 kB │ gzip:  1.12 kB
.nuxt/dist/client/_nuxt/entry.8768f868.css                      15.27 kB │ gzip:  3.85 kB
.nuxt/dist/client/_nuxt/_plugin-vue_export-helper.c27b6911.js    0.09 kB │ gzip:  0.10 kB
.nuxt/dist/client/_nuxt/404.f7a77ec2.js                          0.48 kB │ gzip:  0.37 kB
.nuxt/dist/client/_nuxt/default.b14d229f.js                      0.72 kB │ gzip:  0.55 kB
.nuxt/dist/client/_nuxt/error-component.19636357.js              1.22 kB │ gzip:  0.63 kB
.nuxt/dist/client/_nuxt/error-500.08e2e397.js                    1.93 kB │ gzip:  1.02 kB
.nuxt/dist/client/_nuxt/error-404.aa1f8d51.js                    2.27 kB │ gzip:  1.18 kB
.nuxt/dist/client/_nuxt/index.3fff210c.js                       49.57 kB │ gzip: 19.15 kB
.nuxt/dist/client/_nuxt/entry.b264dfbf.js                      138.46 kB │ gzip: 51.59 kB
✔ Client built in 540106ms                                                                                    10:04:44
ℹ Building server...                                                                                          10:04:44
vite v4.0.4 building SSR bundle for production...
✓ 80 modules transformed.
.nuxt/dist/server/_nuxt/_plugin-vue_export-helper-cc2b3d55.js   0.25 kB │ map:   0.13 kB
.nuxt/dist/server/_nuxt/404-123ef5c3.js                         1.26 kB │ map:   0.58 kB
.nuxt/dist/server/_nuxt/island-renderer-b181f9d0.js             1.28 kB │ map:   1.58 kB
.nuxt/dist/server/_nuxt/default-b65e3a79.js                     1.86 kB │ map:   0.58 kB
.nuxt/dist/server/_nuxt/error-component-a99e1669.js             1.99 kB │ map:   2.66 kB
.nuxt/dist/server/_nuxt/error-500-35954098.js                   3.14 kB │ map:   3.76 kB
.nuxt/dist/server/_nuxt/error-404-95cebc80.js                   4.00 kB │ map:   5.80 kB
.nuxt/dist/server/_nuxt/index-b68e5711.js                      26.21 kB │ map: 278.56 kB
.nuxt/dist/server/server.mjs                                   55.28 kB │ map: 173.41 kB
✔ Server built in 6456ms                                                                                      10:04:50
✔ Generated public .output/public                                                                       nitro 10:04:50
ℹ Building Nitro Server (preset: node-server)                                                           nitro 10:04:50
✔ Nitro server built                                                                                    nitro 10:05:04
  ├─ .output/server/package.json (1.52 kB) (585 B gzip)
  ├─ .output/server/index.mjs (526 B) (269 B gzip)
  ├─ .output/server/chunks/rollup/_virtual_head-static.mjs.map (111 B) (112 B gzip)
  ├─ .output/server/chunks/rollup/_virtual_head-static.mjs (301 B) (217 B gzip)
  ├─ .output/server/chunks/pageview.mjs.map (301 B) (188 B gzip)
  ├─ .output/server/chunks/pageview.mjs (237 B) (184 B gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs.map (73.6 kB) (5.32 kB gzip)
  ├─ .output/server/chunks/nitro/node-server.mjs (23.4 kB) (6.94 kB gzip)
  ├─ .output/server/chunks/nitro/config.mjs.map (1.99 kB) (591 B gzip)
  ├─ .output/server/chunks/nitro/config.mjs (1.47 kB) (671 B gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs.map (19.6 kB) (3.43 kB gzip)
  ├─ .output/server/chunks/handlers/renderer.mjs (15.8 kB) (4.83 kB gzip)
  ├─ .output/server/chunks/error-500.mjs.map (1.04 kB) (376 B gzip)

                                                                                                              14:19:33
Nuxi 3.1.1                                                                                                    14:19:33
Nuxt 3.1.1 with Nitro 2.1.1-27917995.930438a                                                                  14:19:33
                                                                                                              14:19:37
  > Local:    http://localhost:3000/ 
  > Network:  http://10.10.10.10:3000/


 WARN  [@vue/reactivity-transform] Reactivity transform is an experimental feature.                           14:19:42
Experimental features may change behavior between patch versions.
It is recommended to pin your vue dependencies to exact versions to avoid breakage.
You can follow the proposal's status at https://github.com/vuejs/rfcs/discussions/369.


✔ Nitro built in 2365 ms                                                                                nitro 14:19:48

 ERROR  Failed to fetch web fonts                                                                             14:28:25


 ERROR  request to https://fonts.googleapis.com/css2?family=DM+Sans&family=DM+Serif+Display&family=DM+Mono&display=swap failed, reason: connect ETIMEDOUT 64.233.164.95:443 ()

  at async $fetchRaw2 (node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
  at async $fetchRaw2 (node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
  at async $fetchRaw2 (node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)


 WARN  Sourcemap for "/__uno.css" points to missing source files                                              14:28:26

ℹ Vite client warmed up in 526896ms                                                                           14:28:27
✔ Vite server hmr 27 files in 2996.053ms
```
Site is running, no icons. Maybe I'm doing something wrong?

**Comment by android116** [comment]
> Hey @android116
> 
> Unfortunately icons are not loaded by a CDN from Google fonts, they are installed locally with NPM using Iconify, have you run "npm run dev"? That should work for local development

This is what I have when I do **npm run dev**

```
Nuxi 3.1.1                                                                                                    14:53:12
Nuxt 3.1.1 with Nitro 2.1.1-27917995.930438a                                                                  14:53:12
                                                                                                              14:53:15
  > Local:    http://localhost:3000/ 
  > Network:  http://10.14.4.25:3000/                                                                         14:53:12


 WARN  [@vue/reactivity-transform] Reactivity transform is an experimental feature.                           14:53:20
Experimental features may change behavior between patch versions.
It is recommended to pin your vue dependencies to exact versions to avoid breakage.
You can follow the proposal's status at https://github.com/vuejs/rfcs/discussions/369.


✔ Nitro built in 2384 ms                                                                                nitro 14:53:26

 ERROR  Failed to fetch web fonts                                                                             15:02:04


 ERROR  request to https://fonts.googleapis.com/css2?family=DM+Sans&family=DM+Serif+Display&family=DM+Mono&display=swap failed, reason: connect ETIMEDOUT 64.233.161.95:443 ()

  at async $fetchRaw2 (node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
  at async $fetchRaw2 (node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
  at async $fetchRaw2 (node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)


 WARN  Sourcemap for "/__uno.css" points to missing source files                                              15:02:05

ℹ Vite client warmed up in 525957ms 
```

Site is running, no icons. Maybe I'm doing something wrong?

**Comment by android116** [comment]
> Hey @android116
> 
> Unfortunately icons are not loaded by a CDN from Google fonts, they are installed locally with NPM using Iconify, have you run "npm run dev"? That should work for local development


This is what I have when I do **npm run dev**

```
Nuxi 3.1.1                                                                                                    14:53:12
Nuxt 3.1.1 with Nitro 2.1.1-27917995.930438a                                                                  14:53:12
                                                                                                              14:53:15
  > Local:    http://localhost:3000/ 
  > Network:  http://10.10.10.10:3000/                                                                         14:53:12


 WARN  [@vue/reactivity-transform] Reactivity transform is an experimental feature.                           14:53:20
Experimental features may change behavior between patch versions.
It is recommended to pin your vue dependencies to exact versions to avoid breakage.
You can follow the proposal's status at https://github.com/vuejs/rfcs/discussions/369.


✔ Nitro built in 2384 ms                                                                                nitro 14:53:26

 ERROR  Failed to fetch web fonts                                                                             15:02:04


 ERROR  request to https://fonts.googleapis.com/css2?family=DM+Sans&family=DM+Serif+Display&family=DM+Mono&display=swap failed, reason: connect ETIMEDOUT 64.233.161.95:443 ()

  at async $fetchRaw2 (node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
  at async $fetchRaw2 (node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
  at async $fetchRaw2 (node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)


 WARN  Sourcemap for "/__uno.css" points to missing source files                                              15:02:05

ℹ Vite client warmed up in 525957ms 
```

Site is running, no icons. Maybe I'm doing something wrong?
